
export const contestTypes = {
    CONTESTS_REQUEST: 'CONSTESTS_REQUEST',    
    CONTESTS_SUCCESS: 'CONSTESTS_SUCCESS',    
    CONTESTS_FAILURE: 'CONSTESTS_SUCCESS', 
    
    ACTIVE_CONTEST_REQUEST: 'ACTIVE_CONTEST_REQUEST',
    ACTIVE_CONTEST_SUCCESS: 'ACTIVE_CONTEST_SUCCESS',
    ACTIVE_CONTEST_FAILURE: 'ACTIVE_CONTEST_FAILURE',

    CONTEST_PAYMENTS_REQUEST: 'CONTEST_PAYMENTS_REQUEST',
    CONTEST_PAYMENTS_SUCCESS: 'CONTEST_PAYMENTS_SUCCESS',
    CONTEST_PAYMENTS_FAILURE: 'CONTEST_PAYMENTS_FAILURE',
}