
export const createUserTypes = {
    STORE_REQUEST: 'STORE_REQUEST',
    STORE_SUCCESS: 'STORE_SUCCESS',
    STORE_FAILURE: 'STORE_FAILURE',

    STORE_SMS_REQUEST: 'STORE_SMS_REQUEST',
    STORE_SMS_SUCCESS: 'STORE_SMS_SUCCESS',
    STORE_SMS_FAILURE: 'STORE_SMS_FAILURE',
    
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    
    COUNTRIES_REQUEST: 'COUNTRIES_REQUEST',
    COUNTRIES_SUCCESS: 'COUNTRIES_SUCCESS',
    COUNTRIES_FAILURE: 'COUNTRIES_FAILURE',
    
    SENDSMS_REQUEST: 'SENDSMS_REQUEST',
    SENDSMS_SUCCESS: 'SENDSMS_SUCCESS',
    SENDSMS_FAILURE: 'SENDSMS_FAILURE',

    CONFIRM_SMS_REQUEST: 'CONFIRM_SMS_REQUEST',
    CONFIRM_SMS_SUCCESS: 'CONFIRM_SMS_SUCCESS',
    CONFIRM_SMS_FAILURE: 'CONFIRM_SMS_FAILURE',
}