
export const ticketTypes = {
    GET_REFFLED_REQUEST: 'GET_REFFLED_REQUEST',
    GET_REFFLED_SUCCESS: 'GET_REFFLED_SUCCESS',
    GET_REFFLED_FAILURE: 'GET_REFFLED_FAILURE',

    GET_HISTORY_REQUEST: 'GET_HISTORY_REQUEST',
    GET_HISTORY_SUCCESS: 'GET_HISTORY_SUCCESS',
    GET_HISTORY_FAILURE: 'GET_HISTORY_FAILURE',
}