
export const userTypes = {
    STORE_USER: 'STORE_USER',

    TURNOFF_RETURN: 'TURNOFF_RETURN',

    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_FAILURE: 'UPDATE_FAILURE',
    
    CARDSDATA_REQUEST: 'CARDSDATA_REQUEST',
    CARDSDATA_SUCCESS: 'CARDSDATA_SUCCESS',
    CARDSDATA_FAILURE: 'CARDSDATA_FAILURE',
}